"""Generate a plain-text clinical-style report from classifier output."""

from datetime import datetime


def generate_report(result: dict, filename: str) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "=" * 60,
        "PANCREATIC CT CLASSIFICATION REPORT",
        "RESEARCH PROTOTYPE — NOT FOR CLINICAL USE",
        "=" * 60,
        f"Date/time : {now}",
        f"File      : {filename}",
        "",
    ]

    if not result.get("is_pancreas"):
        lines += [
            "ORGAN GATE RESULT: FAILED",
            f"Detected as  : {result.get('detected_as', 'Unknown')}",
            f"Confidence   : {result.get('organ_confidence', 0):.0%}",
            "",
            "Image does not appear to contain pancreatic CT anatomy.",
            "Upload an axial CT slice showing the upper abdomen.",
        ]
    else:
        verdict = result.get("verdict", "N/A")
        conf    = result.get("confidence", 0)
        lines += [
            f"CLASSIFICATION: {verdict}",
            f"Confidence   : {conf:.0%}",
            "",
            "CLASS PROBABILITIES",
            "-" * 30,
        ]
        for cls, score in sorted(result.get("scores", {}).items(), key=lambda x: -x[1]):
            bar = "█" * int(score * 20)
            lines.append(f"  {cls:<22} {bar:<20} {score:.0%}")

        lines += [
            "",
            "FEATURE ANALYSIS",
            "-" * 30,
        ]
        for fname, fdata in result.get("features", {}).items():
            lines.append(f"  {fname:<30} {fdata['label']} [{fdata['level'].upper()}]")

        lines += [
            "",
            "INTERPRETATION",
            "-" * 30,
            result.get("explanation", ""),
            "",
        ]

        # Clinical guidance
        guidance = {
            "PDAC":        "ACTION: Refer to pancreatic surgery / HPB team urgently.\n"
                           "        Consider CT staging, CA 19-9, bilirubin, MDT review.",
            "Non-PDAC":    "ACTION: Routine follow-up. Repeat imaging in 12 months\n"
                           "        if incidental finding.",
            "IPMN":        "ACTION: MRI/MRCP in 3–6 months. EUS if worrisome features\n"
                           "        (nodules, rapid growth, jaundice).",
            "CP":          "ACTION: Gastroenterology review. Enzyme replacement therapy,\n"
                           "        pain management, alcohol cessation if relevant.",
            "Indeterminate":"ACTION: Radiologist review required. Consider EUS / MRCP\n"
                            "        for further characterisation.",
        }
        action = guidance.get(verdict, "")
        if action:
            lines += [action, ""]

    lines += [
        "=" * 60,
        "DISCLAIMER: This output is generated by a research AI prototype.",
        "It has NOT been validated for clinical use. Do not use for",
        "diagnostic or treatment decisions.",
        "=" * 60,
    ]

    return "\n".join(lines)
